import { Link } from 'react-router-dom';
import { ArrowRight, CalendarDays, Flame, Wind, Sparkles } from 'lucide-react';
import { Brand } from '../components/Brand';
import family from '../assets/easy-breezy-family-hero-final.webp';
import duct from '../assets/service/easy-breezy-duct-technician.webp';
import dryer from '../assets/service/easy-breezy-dryer-technician.webp';
import chimney from '../assets/service/easy-breezy-chimney-technician.webp';
const services=[[Wind,'Air duct cleaning'],[Sparkles,'Dryer vent cleaning'],[Flame,'Chimney cleaning']];
export default function RedesignThree(){return <main className="r3"><header><Link to="/"><Brand/></Link><nav><Link to="/services">Services</Link><Link to="/before-after">Results</Link><Link to="/service-areas">Service areas</Link></nav><Link className="r3-button" to="/booking">Get Free Quote <ArrowRight/></Link></header><section className="r3-hero"><div><h1>A fresher home<br/>starts with <span>clean air ducts.</span></h1><p>Professional air duct, dryer vent, and chimney service for homes that deserve clean, comfortable air.</p><div className="r3-actions"><Link className="r3-button" to="/booking">Get Free Quote <ArrowRight/></Link><Link className="r3-secondary" to="/services">Explore services</Link></div><Link className="r3-availability" to="/booking"><CalendarDays/><b>Check availability</b><span>See your next appointment →</span></Link></div><img src={family} alt="Family relaxing in a clean home"/></section><section className="r3-services"><strong>How can we help?</strong>{services.map(([Icon,text])=><Link to="/services" key={text}><Icon/><span>{text}</span></Link>)}</section><section className="r3-proof"><div><h2>Real work. Real care.</h2><p>Clear expectations from quote to clean finish.</p></div><div>{[duct,dryer,chimney].map((src,i)=><img key={src} src={src} alt={["Air duct cleaning","Dryer vent cleaning","Chimney cleaning"][i]}/>)}</div></section><section className="r3-book"><div><h2>Ready for cleaner air?</h2><p>Tell us what you need and we’ll follow up with a clear estimate.</p></div><Link className="r3-button" to="/booking">Request a quote <ArrowRight/></Link></section><footer><Brand/><p>Professional air duct, dryer vent and chimney cleaning for Maryland and Washington, DC.</p></footer></main>}
