import { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import ServiceAreaMap from '../components/ServiceAreaMap.jsx';
import { getViewerLocationName, useViewerLocation } from '../hooks/useViewerLocation';
const pages = {'air-duct-cleaning':['Air Duct Cleaning','Professional Air Duct Cleaning in {loc}','A clear, thorough approach to cleaning the ductwork that serves your home or business.'],'dryer-vent-cleaning':['Dryer Vent Cleaning','Professional Dryer Vent Cleaning in {loc}','We remove lint buildup and explain what we found so you know what was cleaned.'],'chimney-cleaning':['Chimney Cleaning','Chimney Cleaning & Sweep Services in {loc}','Straightforward chimney sweeping and cleaning service with clear next steps.'],'furnace-cleaning':['Furnace Cleaning','Furnace Cleaning in {loc}','Learn what furnace and blower cleaning includes and when it may make sense.'],'carpet-cleaning':['Carpet Cleaning','Professional Carpet Cleaning in {loc}','Easy scheduling and straightforward professional carpet cleaning estimates.'],'commercial-air-duct-cleaning':['Commercial Air Duct Cleaning','Commercial Air Duct Cleaning in {loc}','Cleaning plans for offices, retail, multi-unit properties and other facilities.'],pricing:['Pricing','Straightforward pricing for cleaner air','Your estimate reflects the service, system size, access, and any approved add-ons. We explain the scope before work begins.'],'before-after':['Before & After','Real Easy Breezy before-and-after results','This gallery will feature genuine Easy Breezy job photos, grouped by service and local area as they are collected.'],'service-areas':['Service Areas','Air duct cleaning service areas in {loc}','Easy Breezy serves homeowners and businesses across {loc}.']};
const titleize=(value='')=>value.replace(/-md$/,', MD').replace(/-/g,' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());
export default function SeoPage({location}) {
  const params=useParams();
  const isServiceAreas=params.page==='service-areas';
  const viewerLocation=useViewerLocation();
  const hasViewerCity=viewerLocation?.city && viewerLocation.countryCode==='US';
  const viewerLocationName=hasViewerCity?getViewerLocationName(viewerLocation):'';
  const loc=viewerLocationName||'Maryland & Washington, DC';
  const baseItem=location?[`${titleize(params.location)} Service Area`,`Air Duct Cleaning in ${titleize(params.location)}`,`Easy Breezy provides air duct and dryer vent cleaning in and around ${titleize(params.location)}. Contact us for a clear, local estimate.`]:pages[params.page];
  const item=isServiceAreas && viewerLocationName
    ? [baseItem?.[0], `Air Duct Cleaning Near ${viewerLocationName}`, `Easy Breezy provides air duct, dryer vent, chimney and furnace cleaning for ${viewerLocationName} and the surrounding Maryland & DC area.`]
    : baseItem && [baseItem[0], baseItem[1]?.replace('{loc}', loc), baseItem[2]?.replace('{loc}', loc)];
  const heading=item?.[1]; const intro=item?.[2];
  useEffect(()=>{if(!heading)return; document.title=`${heading} | Easy Breezy`; const description=document.querySelector('meta[name="description"]'); if(description)description.setAttribute('content',intro);},[heading,intro]);
  if(!item)return <section className="page"><h1>Page coming soon</h1></section>;
  const [label]=item;
  return <main className="seo-page page"><nav className="breadcrumbs"><Link to="/">Home</Link><span> / </span><span>{label}</span></nav><h1>{heading}</h1><p className="lede">{intro}</p>{!isServiceAreas&&<section className="seo-copy"><h2>What Easy Breezy includes</h2><p>We begin with a clear conversation about your home or property, then confirm the service scope, access and timing. Our team explains the work in plain language and treats your space with care.</p><h2>Request a clear estimate</h2><p>Every system and home is different. Tell us what you need, and we will help identify the appropriate service and next step.</p><Link className="button" to="/booking">Get Free Quote <span>→</span></Link></section>}{params.page==='pricing'&&<section className="seo-copy"><h2>How we put together your estimate</h2><p>Before we quote a price, we take a few things into account: the size of your system and the number of vents or runs involved, how easy the ductwork, chimney or vents are to access, the current condition of the system, and any add-on services you would like included, such as sanitizing or dryer vent repair. Two homes with the same square footage can need very different amounts of work, so we look at your actual setup rather than guessing from a flat rate.</p><h2>Free estimates, no hidden fees</h2><p>Estimates are free and provided before any work begins. We walk you through exactly what is included, answer your questions, and get your approval on the scope and price up front. If anything changes once we start, such as an unexpected repair need, we explain it and get your okay before doing any additional work or charging anything extra.</p><h2>How to request one</h2><p>The quickest way to get a number for your home is to tell us a little about your system and property, and we will follow up with clear next steps.</p></section>}{isServiceAreas&&<section className="area-links"><h2>{viewerLocationName?`Do we cover ${viewerLocationName}?`:'Your service area'}</h2><ServiceAreaMap /><Link className="button area-links-cta" to="/booking">Get Free Quote <span>→</span></Link></section>}</main>;
}
